channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.2.2
- pip:
  - mlflow<3,>=2.2
  - category-encoders==2.6.0
  - cloudpickle==2.0.0
  - databricks-automl-runtime==0.2.16
  - holidays==0.19
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - typing-extensions==4.3.0
  - xgboost==1.7.4
name: mlflow-env
